version: '3.9'

networks:
    localdev:
        name: localdev
services:
    api:
        build: .
        restart: always
        ports:
            - "2600:80"
        networks:
            - localdev